---
- name: Changing password
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/env python3.6"
  hosts: localhost
  tasks:
    - set_fact:
        vm_name: "ansibletest.tom.future.lab"
        vm_user: "root"
        vm_pass: "changeme123"
        vm_new_pass: "'success1!'"
        datacenter: "CMP1-MGMT"
        vcenter: "vc-mgmt.tom.future.lab"
        vcenter_user: "ansible_test@tom.future.lab"
        vcenter_pass: "SSMzLp6Ep5"
        
    - name: Run command inside a vm
      vmware_vm_shell:
        hostname: "{{ vcenter }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        folder: /vm
        vm_id: "{{ vm_name }}"
        vm_username: "{{ vm_user }}"
        vm_password: "{{ vm_pass }}"
        vm_shell: /bin/echo
        vm_shell_args: " root:{{ vm_new_pass }} | /usr/sbin/chpasswd"
        vm_shell_env:
          - "PATH=/bin"
        vm_shell_cwd: "/tmp"
      delegate_to: localhost